# Generated by Django 4.2.7 on 2024-02-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('productdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.userdata')),
            ],
        ),
    ]
